# Image is based on Debian Slim
FROM node:18-slim

RUN mkdir -p /app

WORKDIR /app

RUN apt-get update && apt-get install -y \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

COPY . .

RUN npm install --production

CMD ["node", "src/cluster.js"]